services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"

  train-model:
    build:
      context: ./FastAPI
      dockerfile: Dockerfile
    depends_on:
      fastapi:
        condition: service_started

    command: python train_model.py
    volumes:
      - ./FastAPI:/app

  fastapi:
    build:
      context: ./FastAPI
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      API_KEY: 1W1NOQU2N2I0OXSY
      DATABASE_URL: sqlite:///earnings.db
      CORS_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000"
    volumes:
      - ./FastAPI:/app

volumes:
  earnings_data: